AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda subscriber for DynamoDB Streams (chat side effects)"

Parameters:
  TableName:
    Type: String
    Default: chat_app_table
  LambdaFunctionName:
    Type: String
    Default: chat-dynamodb-stream-processor
  LambdaCodeS3Bucket:
    Type: String
  LambdaCodeS3Key:
    Type: String

Resources:
  ChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  StreamProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: stream-logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: ddb-stream-read
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt ChatTable.StreamArn

  StreamProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt StreamProcessorRole.Arn
      Timeout: 30
      MemorySize: 256
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key

  StreamToLambdaMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ChatTable.StreamArn
      FunctionName: !GetAtt StreamProcessorLambda.Arn
      StartingPosition: LATEST
      BatchSize: 10
      MaximumRetryAttempts: 2
      Enabled: true

Outputs:
  ChatTableName:
    Value: !Ref ChatTable
  ChatTableStreamArn:
    Value: !GetAtt ChatTable.StreamArn
  StreamProcessorLambdaArn:
    Value: !GetAtt StreamProcessorLambda.Arn
